import type { MatchFormFields } from "./buildMatchBody";

const emptyForm = (): MatchFormFields => ({
  playerType: "hitter",
  primaryPosition: "",
  secondaryPosition: "",
  gradYear: "",
  handedness: "",
  gpa: "",
  preferredStatesCsv: "",
  preferredDivisionsCsv: "",
  preferredConferencesCsv: "",
  schoolTypePreference: "",
  schoolSizePreference: "",
  tuitionPreference: "",
  athleticFitW: "",
  locationFitW: "",
  schoolFitW: "",
  affordabilityFitW: "",
  fastballVelocity: "",
  topVelocity: "",
  strikePercentage: "",
  avgExitVelocity: "",
  maxExitVelocity: "",
  sixtyTime: "",
  infThrowingVelocity: "",
  ofThrowingVelocity: "",
  catcherPopTime: "",
  catcherArmVelocity: "",
  heightInches: "",
  weightLbs: "",
});

export type PresetDef = {
  id: string;
  label: string;
  apply: () => MatchFormFields;
};

export const MATCH_PRESETS: PresetDef[] = [
  {
    id: "minimal",
    label: "Minimal valid",
    apply: () => ({
      ...emptyForm(),
      playerType: "hitter",
      primaryPosition: "C",
    }),
  },
  {
    id: "full-pitcher",
    label: "Full pitcher",
    apply: () => ({
      ...emptyForm(),
      playerType: "pitcher",
      primaryPosition: "RHP",
      secondaryPosition: "OF",
      gradYear: "2026",
      handedness: "R/R",
      gpa: "3.7",
      preferredStatesCsv: "TX, FL",
      preferredDivisionsCsv: "D1",
      preferredConferencesCsv: "SEC, AAC",
      schoolTypePreference: "Public",
      schoolSizePreference: "large",
      tuitionPreference: "moderate",
      athleticFitW: "0.3",
      locationFitW: "0.3",
      schoolFitW: "0.2",
      affordabilityFitW: "0.2",
      fastballVelocity: "88",
      topVelocity: "90",
      strikePercentage: "62",
      heightInches: "73",
      weightLbs: "190",
    }),
  },
  {
    id: "full-hitter-ss",
    label: "Full hitter (SS)",
    apply: () => ({
      ...emptyForm(),
      playerType: "hitter",
      primaryPosition: "SS",
      secondaryPosition: "2B",
      gradYear: "2027",
      handedness: "R/R",
      gpa: "3.4",
      preferredStatesCsv: "TX",
      preferredDivisionsCsv: "D1",
      preferredConferencesCsv: "Big 12",
      schoolTypePreference: "Public",
      schoolSizePreference: "large",
      tuitionPreference: "low",
      athleticFitW: "0.3",
      locationFitW: "0.25",
      schoolFitW: "0.25",
      affordabilityFitW: "0.2",
      avgExitVelocity: "85",
      maxExitVelocity: "92",
      sixtyTime: "6.9",
      infThrowingVelocity: "82",
      heightInches: "71",
      weightLbs: "175",
    }),
  },
  {
    id: "full-catcher",
    label: "Full catcher",
    apply: () => ({
      ...emptyForm(),
      playerType: "hitter",
      primaryPosition: "C",
      gradYear: "2026",
      handedness: "R/R",
      gpa: "3.2",
      preferredStatesCsv: "FL, GA",
      preferredDivisionsCsv: "D1, D2",
      preferredConferencesCsv: "SEC, Sun Belt",
      schoolTypePreference: "Public",
      schoolSizePreference: "large",
      tuitionPreference: "low",
      athleticFitW: "0.35",
      locationFitW: "0.25",
      schoolFitW: "0.2",
      affordabilityFitW: "0.2",
      avgExitVelocity: "83",
      maxExitVelocity: "90",
      sixtyTime: "7.3",
      catcherPopTime: "1.95",
      catcherArmVelocity: "78",
      heightInches: "72",
      weightLbs: "195",
    }),
  },
  {
    id: "full-outfielder",
    label: "Full outfielder",
    apply: () => ({
      ...emptyForm(),
      playerType: "hitter",
      primaryPosition: "CF",
      secondaryPosition: "RF",
      gradYear: "2027",
      handedness: "L/L",
      gpa: "3.5",
      preferredStatesCsv: "CA, AZ",
      preferredDivisionsCsv: "D1",
      preferredConferencesCsv: "Pac-12",
      schoolTypePreference: "Public",
      schoolSizePreference: "large",
      tuitionPreference: "moderate",
      athleticFitW: "0.3",
      locationFitW: "0.3",
      schoolFitW: "0.2",
      affordabilityFitW: "0.2",
      avgExitVelocity: "88",
      maxExitVelocity: "96",
      sixtyTime: "6.7",
      ofThrowingVelocity: "88",
      heightInches: "74",
      weightLbs: "185",
    }),
  },
];
